opensilex-core:
    debug: false
    scheme: http
    host: localhost
    port: 8080
    basePath: /opensilex-core/rest
    defaultLanguage: en
        
opensilex-core-rdf4j:
    host: localhost
    port: 8080
    repository: repository
    path: rdf4j-server

opensilex-core-mongo:
    host: localhost
    port: 27017
    database: database